### PR TITLE
Fix problem with "Invalid modifier manager" by replacing ember-ref-modifier with ember-ref-bucket 

### PR DESCRIPTION
**Pull request by bracke**

### CODE REVIEW

**Comment by ef4** [comment]
I'm hitting these issues too, and I tried this PR. I think it's not quite complete because ember-ref-bucket requires you to use a `@ref` decorator on the JS side, like:

```js
import { ref } from 'ember-ref-bucket';
export default class MaskedInputComponent extends Component {
  @ref("inputEl") inputEl ;
}
```

**Comment by ef4** [comment]
This is the same idea but with the `@ref` modifier: https://github.com/networkteam/ember-cli-maskedinput/pull/21

That was enough to get it working for me.

**Comment by hlubek** [comment]
Thx for the fix! I'll have a look at it and how the dependencies and tests need to change. Maybe we can use peer dependencies to prevent issues with multiple `ember-modifier` versions.

**Comment by bracke** [comment]
@hlubek I wish I could help, but I know nothing about dependency management.

**Pull request merged**
